"""
FastAPI backend for the CSE Regime-Aware Portfolio research demo.

Run from the project root (so `backend` and `src` are both importable):
    python -m uvicorn backend.main:app --reload --port 8000
"""
import logging
import os
from datetime import datetime, timedelta

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware

from . import config, cse_client, inference
from .backtest_data import get_backtest_dataset

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("backend")

app = FastAPI(title="CSE Regime-Aware Portfolio — Research Demo API")

# Demo-only: wide open CORS so the Vite dev server (or a static build served
# from anywhere) can call this without extra configuration.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/api/health")
def health():
    try:
        _, _, manifest = inference.load_bundle()
        checkpoint_available = True
        checkpoint_filename = manifest.get("checkpoint_filename")
    except inference.ModelNotReadyError:
        checkpoint_available = False
        checkpoint_filename = None

    return {
        "status": "ok",
        "checkpoint_available": checkpoint_available,
        "checkpoint_filename": checkpoint_filename,
        "scaler_available": os.path.exists(config.SCALER_PATH),
        "manifest_available": os.path.exists(config.MANIFEST_PATH),
        "backtest_data_available": os.path.exists(config.TEST_WEIGHTS_PATH),
    }


@app.get("/api/model-info")
def model_info():
    return {
        "assets": [
            {"ticker": ticker, "name": name}
            for ticker, name in config.ASSET_DISPLAY_NAMES.items()
        ],
        "initial_capital": config.INITIAL_CAPITAL,
        "window_size": config.WINDOW_SIZE,
        "disclaimer": (
            "Research prototype — allocations are generated by a model "
            "trained on historical CSE banking-sector data (10 assets). "
            "Not investment advice."
        ),
    }


@app.get("/api/backtest")
def backtest():
    """Full test-set day-by-day weights + summary metrics. Needs no
    checkpoint — reads results/test_raw_weights.xlsx + test_summary.json,
    already produced by `python main.py --mode train` / `--mode backtest`."""
    try:
        return get_backtest_dataset()
    except FileNotFoundError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc


@app.get("/api/cse/test")
def cse_test(symbol: str = "COMB", days: int = 30):
    """Diagnostic-only: fetch one symbol's recent history straight from CSE,
    independent of the model bundle. Use this to verify the access token
    and response shape without needing a trained checkpoint yet."""
    to_date = datetime.now()
    from_date = to_date - timedelta(days=days)
    try:
        rows = cse_client.fetch_symbol_history(symbol, from_date, to_date)
    except cse_client.CSEAuthError as exc:
        raise HTTPException(status_code=401, detail=str(exc)) from exc
    except RuntimeError as exc:
        raise HTTPException(status_code=502, detail=str(exc)) from exc

    return {"symbol": symbol, "n_rows": len(rows), "rows": rows}


@app.get("/api/live/today")
def live_today():
    """Live, current-day allocation. Needs BOTH a promoted model bundle
    (checkpoint + scaler + manifest, via scripts/export_model_bundle.py)
    AND enough CSE history to build one window — neither is confirmed
    working yet, so this reports exactly why it can't run rather than
    fabricating a result."""
    try:
        _, _, manifest = inference.load_bundle()
    except inference.ModelNotReadyError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc

    tickers = manifest["asset_names"]
    min_days = manifest.get("min_trading_days_required", 60)
    to_date = datetime.now()
    from_date = to_date - timedelta(days=int(min_days * 1.6))  # pad for weekends/holidays

    try:
        history = cse_client.fetch_all_history(tickers, from_date, to_date)
    except cse_client.CSEAuthError as exc:
        raise HTTPException(status_code=401, detail=str(exc)) from exc
    except RuntimeError as exc:
        raise HTTPException(status_code=502, detail=str(exc)) from exc

    # Fetching real history is confirmed above; assembling it into the
    # (T, n_assets) price/volume matrices inference.predict_weights()
    # expects — aligning dates across all 10 symbols, handling any gaps —
    # is the next step, not yet wired up.
    raise HTTPException(
        status_code=501,
        detail=(
            f"Fetched CSE history for {len(history)}/{len(tickers)} assets "
            f"successfully, but assembling it into the model's expected "
            f"input format isn't wired up yet — this is the next step, not "
            f"a data problem anymore."
        ),
    )
